---
title: "Sample Blog Post"
author: "R-Ladies Chicago"
date: 2018-07-01T21:13:14-05:00
categories: ["R"]
tags: ["community", "rladies"]
---

Hello! This is a sample blog post. Be sure to update the header (i.e. change the title, put your name as the author, and include any relevant tags) and use the following naming convention when submitting your file:  

**YYYY-MM-DD-LASTNAME.Rmd**  
  
  
Your text goes here!  
  
Some relevant tags you might want to use:  
  
* rladies  
* a study group name  
* data/package name  
  
*The R-Ladies Chicago organizers may add tags they feel are relevant!*  
  
If using a dataset that isn't in R, please do your best to have your data pulled in remotely. In an ideal scenario, you provide a single `.Rmd` file that can be knitted and added to the site (without any other necessary files).   
  
One way to do this is via `RCurl`:  
  
```{r, eval=FALSE}
Require("RCurl")
library(RCurl)
DAT_Rladies<-read.csv(text=getURL("https://raw.githubusercontent.com/rladies-chicago/2018-12-05-meetup/master/data/meetup.csv")) 
```
   

  
#### About the Author:  
  
Please be sure to include a 2-sentence bio about yourself at the end of your blog post! Include your name, job title and organization (if applicable), and a quick summary of your experience with R.  
